network: !Testnet
key_server_object_id: '0x0688650cf0b28882e607ae43df1e95e769f9b2f689cf90d68c715b3e08e28c70'
# Minimum client SDK version required (optional, defaults to >=0.9.6)
sdk_version_requirement: '>=0.9.6'
